# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 09:23
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('Head', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='League',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255, null=True, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Match',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ronde', models.PositiveSmallIntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TeamReport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('TD', models.PositiveSmallIntegerField(null=True)),
                ('cas', models.PositiveSmallIntegerField(null=True)),
                ('passes', models.PositiveSmallIntegerField(null=True)),
                ('Coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='report', to='tournament.Coach')),
                ('match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='team_reports', to='tournament.Match')),
            ],
        ),
    ]
