# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 09:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0001_initial'),
    ]

    operations = [
        #migrations.RunPython(create_admin_user),
        #migrations.RunPython(load_datas),
    ]
