# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 09:51
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0002_auto_20170131_0931'),
    ]

    operations = [
        migrations.RenameField(
            model_name='coach',
            old_name='Head',
            new_name='head',
        ),
        migrations.AddField(
            model_name='coach',
            name='league',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, related_name='league_coachs', to='tournament.League'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='match',
            name='table',
            field=models.PositiveSmallIntegerField(null=True),
        ),
    ]
