# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-01-31 14:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0003_auto_20170131_0951'),
    ]

    operations = [
        migrations.AddField(
            model_name='coach',
            name='TD_tot',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='aggros_tot',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='cas_tot',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='interception_tot',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='nb_draw',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='nb_lose',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='nb_win',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='coach',
            name='passes_tot',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teamreport',
            name='aggros',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teamreport',
            name='interception',
            field=models.PositiveSmallIntegerField(null=True),
        ),
        migrations.AddField(
            model_name='teamreport',
            name='is_draw',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamreport',
            name='is_loser',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='teamreport',
            name='is_winner',
            field=models.BooleanField(default=False),
        ),
    ]
