# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 10:20
from __future__ import unicode_literals

from django.db import migrations
from tournament.models import League,Coach
from django.contrib.auth.hashers import make_password
from django.conf import settings
import csv

class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0004_auto_20170131_1411'),
    ]

    operations = [
    ]
