# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-01 12:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0005_auto_20170201_1020'),
    ]

    operations = [
        migrations.RenameField(
            model_name='teamreport',
            old_name='Coach',
            new_name='coach',
        ),
    ]
