# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 08:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0008_auto_20170202_0847'),
    ]

    operations = [
        migrations.AddField(
            model_name='league',
            name='points',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Points'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='TD_tot',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='TD'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='aggros_tot',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Aggros'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='cas_tot',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='cas'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='head',
            field=models.BooleanField(default=False, verbose_name='Tête de série'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='interception_tot',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Int'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='league',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coachs', to='tournament.League', verbose_name='Ligue'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='name',
            field=models.CharField(blank=True, max_length=255, null=True, unique=True, verbose_name='Nom'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='nb_draw',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Nul'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='nb_lose',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Défaites'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='nb_win',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Victoire'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='passes_tot',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Pas'),
        ),
        migrations.AlterField(
            model_name='coach',
            name='points',
            field=models.PositiveSmallIntegerField(null=True, verbose_name='Points'),
        ),
    ]
