# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-03 10:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0009_auto_20170203_0826'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='league',
            options={'verbose_name': 'Ligue'},
        ),
        migrations.AlterModelOptions(
            name='match',
            options={'verbose_name': 'Match'},
        ),
        migrations.RemoveField(
            model_name='teamreport',
            name='cas',
        ),
        migrations.RemoveField(
            model_name='teamreport',
            name='interception',
        ),
        migrations.AddField(
            model_name='teamreport',
            name='interceptions',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='teamreport',
            name='sorties',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamreport',
            name='TD',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamreport',
            name='aggros',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamreport',
            name='passes',
            field=models.PositiveSmallIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='teamreport',
            name='points',
            field=models.PositiveSmallIntegerField(blank=True, default=0, null=True),
        ),
    ]
