# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-05 09:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('tournament', '0010_auto_20170203_1051'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='coach',
            options={'ordering': ('-points',)},
        ),
        migrations.AlterModelOptions(
            name='teamreport',
            options={'verbose_name': 'Rapports de match'},
        ),
    ]
